In [191]:
import pandas as pd
import numpy as np
import csv
import gensim
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.pipeline import Pipeline
from scipy.spatial.distance import cdist
from sklearn.decomposition import PCA


from nltk.stem.wordnet import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from string import punctuation

import seaborn as sns
import nltk
import re
import matplotlib.pyplot as plt

from scipy.spatial import distance
from scipy import sparse

In [28]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import  LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem.porter import *
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

class SentimentAnalysis():

    def __init__(self):        

        columnNames = ["jsonid", "label", "headline_text", "subject", "speaker", "speaker_job_title", "state_info", "party_affiliation", "barely_true_counts", "false_counts", "half_true_counts", "mostly_true_counts", "pants_on_fire_counts", "context","clean", "sentiment_vector","vader_polarity", "sentiment_score"]
        dataTrain = pd.read_csv('input_data/train_sentiment.csv', sep=',', header=None, names = columnNames)
        dataTest = pd.read_csv('input_data/test_sentiment.csv', sep=',', header=None, names = columnNames)

        #dropping columns
        columnsToRemove = ['jsonid', 'label', 'subject', 'speaker','speaker_job_title', 'state_info', 'party_affiliation', 'barely_true_counts', 'false_counts', 'half_true_counts', 'mostly_true_counts', 'pants_on_fire_counts', 'context', 'sentiment_vector']
        dataTrain = dataTrain.drop(columns=columnsToRemove)
        dataTest = dataTest.drop(columns=columnsToRemove)
        dataTrain = dataTrain.iloc[1:] 
        dataTest = dataTest.iloc[1:]
    
    
        tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')

        '''
        self.logR_pipeline = Pipeline([
                ('LogRCV', tfidfV),
                ('LogR_clf',LogisticRegression(solver='liblinear', C=32/100))
                ])
        '''
        
        self.logR_pipeline = Pipeline([
                ('LogRCV', tfidfV),
                ('LogR_clf',RandomForestClassifier(n_estimators=100, max_depth=8, random_state=0))
                ])
        

        self.logR_pipeline.fit(dataTrain['headline_text'],dataTrain['vader_polarity'])
        predicted_LogR = self.logR_pipeline.predict(dataTest['headline_text'])
        score = metrics.accuracy_score(dataTest['vader_polarity'], predicted_LogR)
        print("Sentiment Analysis Model Trained - accuracy:   %0.6f" % score)
        

    def predict(self, text):
        predicted = self.logR_pipeline.predict([text])
        predicedProb = self.logR_pipeline.predict_proba([text])[:,1]
        return bool(predicted), float(predicedProb)
    
    
sa = SentimentAnalysis()
sa.predict("Says the Annies List political group supports third-trimester abortions on demand.")

Sentiment Analysis Model Trained - accuracy:   0.960784

(True, 0.9811315920552556)

In [82]:
import warnings
import nltk.sentiment
warnings.filterwarnings('ignore')

senti = nltk.sentiment.vader.SentimentIntensityAnalyzer()

def print_sentiment_scores(sentence):
    snt = senti.polarity_scores(sentence)
    print("{:-<40} \n{}".format(sentence, str(snt)))

In [83]:
def get_vader_polarity(snt):
    if not snt:
        return None
    elif snt['neg'] > snt['pos'] and snt['neg'] > snt['neu']:
        return -1
    elif snt['pos'] > snt['neg'] and snt['pos'] > snt['neu']:
        return 1
    else:
        return 0

In [159]:
#Function to determine if a text is negative(-1) or postive (1) or neutral (0)
def get_polarity_type(sentence):
    sentimentVector = []
    snt = senti.polarity_scores(sentence)
    sentimentVector.append(get_vader_polarity(snt))
    sentimentVector.append(snt['neg'])
    sentimentVector.append(snt['neu'])
    sentimentVector.append(snt['pos'])
    sentimentVector.append(snt['compound'])
    
    #print(sentimentVector)
    return sentimentVector

In [33]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import  LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem.porter import *
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

class SentimentAnalysis():

    def __init__(self):        

        columnNames = ["jsonid", "label", "headline_text", "subject", "speaker", "speaker_job_title", "state_info", "party_affiliation", "barely_true_counts", "false_counts", "half_true_counts", "mostly_true_counts", "pants_on_fire_counts", "context","clean", "sentiment_vector","vader_polarity", "sentiment_score"]
        sentimentTrain = pd.read_csv('input_data/sentiment/my_train_with_raw.csv')
        sentimentTest = pd.read_csv('input_data/sentiment/my_test_with_raw.csv')
        
        imdb_data = pd.read_csv('input_data/sentiment/imdb_and_liar.csv')
        
        train = pd.read_csv('input_data/train_sentiment.csv')
        test = pd.read_csv('input_data/test_sentiment.csv')
        
        train = imdb_data
        
        tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')

        self.logR_pipeline = Pipeline([
                ('LogRCV', tfidfV),
                ('LogR_clf',LogisticRegression(solver='liblinear', C=32/100))
                ])
        
        self.logR_pipeline = Pipeline([
                ('LogRCV', tfidfV),
                ('LogR_clf',RandomForestClassifier(n_estimators=100, max_depth=5, random_state=0))
                ])

        self.logR_pipeline.fit(train['raw_text'],train['sentiment'])
        predicted_LogR = self.logR_pipeline.predict(test['headline_text'])
        score = metrics.accuracy_score(test['vader_polarity'], predicted_LogR)
        print("Sentiment Analysis Model Trained - accuracy:   %0.6f" % score)
        

    def predict(self, text):
        predicted = self.logR_pipeline.predict([text])
        predicedProb = self.logR_pipeline.predict_proba([text])[:,1]
        return bool(predicted), float(predicedProb)
    
    
sa = SentimentAnalysis()
sa.predict("Says the Annies List political group supports third-trimester abortions on demand.")

Sentiment Analysis Model Trained - accuracy:   0.000000

(True, 0.0011889344080878912)

In [11]:
sentimentTrain = pd.read_csv('input_data/sentiment_train.csv')
sentimentTest = pd.read_csv('input_data/sentiment_test.csv')

train = pd.read_csv('input_data/train_sentiment.csv')
test = pd.read_csv('input_data/test_sentiment.csv')

train_merge = train.merge(sentimentTrain, on = 'clean', how = 'outer')
test_merge = test.merge(sentimentTest, on = 'clean', how = 'outer')

print(test_merge.shape)
test_merge.head()

(1289, 22)

,Unnamed: 0_x,jsonid,label,headline_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,...,mostlytrueocunts,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score,Unnamed: 0_y,sentiment,polarity
0,80.0,2854.json,pants-fire,Rebuilding three high schools will benefit 40 ...,education,carole-smith,Portland schools superintendent,Oregon,none,0.0,...,0.0,1.0,a press briefing,rebuild three high school benefit percent port...,"[0.0, 0.75, 0.25, 0.4588]",0.0,0.4588,80,0.1,0
1,124.0,10147.json,false,On an income cap for recipients of the popular...,education,jason-carter,State Senator,Georgia,democrat,1.0,...,1.0,0.0,forum,incom cap recipe popular hope scholarship,"[0.0, 0.412, 0.588, 0.6908]",1.0,0.6908,124,0.2,0
2,168.0,7744.json,mostly-true,Says states mandated tests come from an Englis...,education,george-lavender,State representative,Texas,republican,0.0,...,1.0,0.0,in Texas House of Representatives debate,say state mandat test come english company,"[0.0, 1.0, 0.0, 0.0]",0.0,0.0000,168,0.0,0
3,181.0,5470.json,true,Pasco County schools have graduation rates sub...,education,heather-fiorentino,superintendent of Pasco County's public schools,Florida,republican,0.0,...,0.0,1.0,a press release,pisco county school graduate rate substantia h...,"[0.0, 1.0, 0.0, 0.0]",0.0,0.0000,181,-0.3,-1
4,187.0,8320.json,mostly-true,Today many Florida teachers are at risk of hav...,education,charlie-crist,0,Florida,democrat,15.0,...,19.0,2.0,a Tampa Bay Times op-ed,today mani florida teacher risk pay impact per...,"[0.241, 0.759, 0.0, -0.3612]",0.0,-0.3612,187,-0.3,-1

In [6]:
sentimentTrain.head()

,Unnamed: 0,clean,sentiment,polarity
0,0,say anni list polit group support third trimme...,-0.7,-1
1,1,decline coal start start natur gas took start ...,-0.4,-1
2,2,hillary clinton agre john mccain vote give geo...,0.2,0
3,3,health care reform legis like mandat free sex ...,0.2,0
4,4,econom turnaround start end term,0.1,0

In [32]:
temp =  pd.read_csv('input_data/sentiment/my_train_with_raw.csv')
train = pd.read_csv('input_data/train_sentiment.csv')
temp = train.merge(temp, how = 'outer')

temp.shape

(10263, 22)

In [50]:
import glob

data = []

for files in glob.glob('/Users/jonathan/Downloads/aclImdb/train/neg/*.txt'):
    data.append(open(files, "r").read())

print(len(data))
neg_df = pd.DataFrame(data)

neg_df['sentiment'] = -1

neg_df.head()

data = []

for files in glob.glob('/Users/jonathan/Downloads/aclImdb/train/pos/*.txt'):
    data.append(open(files, "r").read())

print(len(data))
pos_df = pd.DataFrame(data)
pos_df['sentiment'] = 1
pos_df.head()

12500
12500

                                                   0  sentiment
0  For a movie that gets no respect there sure ar...          1
1  Bizarre horror movie filled with famous faces ...          1
2  A solid, if unremarkable film. Matthau, as Ein...          1
3  It's a strange feeling to sit alone in a theat...          1
4  You probably all already know this by now, but...          1

In [54]:
pos_df.columns = ['raw_text', 'sentiment']
neg_df.columns = ['raw_text', 'sentiment']
df = neg_df.merge(pos_df, how = 'outer')
print(df.shape)
df.head()

df.to_csv('input_data/imdb_sentiment.csv')

(25000, 2)

In [4]:
df = pd.read_csv('input_data/sentiment/imdb_sentiment.csv')
print(df.shape)
df.head()

(25000, 3)

   Unnamed: 0                                           raw_text  sentiment
0           0  Working with one of the best Shakespeare sourc...         -1
1           1  Well...tremors I, the original started off in ...         -1
2           2  Ouch! This one was a bit painful to sit throug...         -1
3           3  I've seen some crappy movies in my life, but t...         -1
4           4  "Carriers" follows the exploits of two guys an...         -1

In [5]:
import re

def cleaning(raw_news):
    import nltk
    
    # 1. Remove non-letters/Special Characters and Punctuations
    news = re.sub("[^a-zA-Z]", " ", raw_news)
    
    # 2. Convert to lower case.
    news =  news.lower()
    
    # 3. Tokenize.
    news_words = nltk.word_tokenize( news)
    
    # 4. Convert the stopwords list to "set" data type.
    stops = set(nltk.corpus.stopwords.words("english"))
    
    # 5. Remove stop words. 
    words = [w for w in  news_words  if not w in stops]
    
    # 6. Lemmentize 
    wordnet_lem = [ WordNetLemmatizer().lemmatize(w) for w in words ]
    
    # 7. Stemming
    stems = [nltk.stem.SnowballStemmer('english').stem(w) for w in wordnet_lem ]
    
    # 8. Join the stemmed words back into one string separated by space, and return the result.
    return " ".join(stems)

In [7]:
df['clean_text'] = ''
for index, row in df.iterrows():
    df.loc[index,'clean_text'] = cleaning(row['raw_text'])
df.head()

,Unnamed: 0,raw_text,sentiment,clean_text
0,0,Working with one of the best Shakespeare sourc...,-1,work one best shakespear sourc film manag cred...
1,1,"Well...tremors I, the original started off in ...",-1,well tremor origin start found movi quit enjoy...
2,2,Ouch! This one was a bit painful to sit throug...,-1,ouch one bit pain sit cute amus premis go hell...
3,3,"I've seen some crappy movies in my life, but t...",-1,seen crappi movi life one must among worst def...
4,4,"""Carriers"" follows the exploits of two guys an...",-1,carrier follow exploit two guy two gal stolen ...

In [8]:
df.to_csv('input_data/sentiment/imdb_sentiment.csv')

In [13]:
sentimentTrain = pd.read_csv('input_data/sentiment/sentiment_train.csv')
sentimentTest = pd.read_csv('input_data/sentiment/sentiment_test.csv')

train = pd.read_csv('input_data/train_sentiment.csv')
test = pd.read_csv('input_data/test_sentiment.csv')

train_merge = train.merge(sentimentTrain, on = 'clean', how = 'outer')
test_merge = test.merge(sentimentTest, on = 'clean', how = 'outer')

print(test_merge.shape)
test_merge.head()

test_merge = test_merge.loc[:,  ['headline_text', 'clean', 'polarity']]

(1289, 22)

,Unnamed: 0_x,jsonid,label,headline_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,...,mostlytrueocunts,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score,Unnamed: 0_y,sentiment,polarity
0,80.0,2854.json,pants-fire,Rebuilding three high schools will benefit 40 ...,education,carole-smith,Portland schools superintendent,Oregon,none,0.0,...,0.0,1.0,a press briefing,rebuild three high school benefit percent port...,"[0.0, 0.75, 0.25, 0.4588]",0.0,0.4588,80,0.1,0
1,124.0,10147.json,false,On an income cap for recipients of the popular...,education,jason-carter,State Senator,Georgia,democrat,1.0,...,1.0,0.0,forum,incom cap recipe popular hope scholarship,"[0.0, 0.412, 0.588, 0.6908]",1.0,0.6908,124,0.2,0
2,168.0,7744.json,mostly-true,Says states mandated tests come from an Englis...,education,george-lavender,State representative,Texas,republican,0.0,...,1.0,0.0,in Texas House of Representatives debate,say state mandat test come english company,"[0.0, 1.0, 0.0, 0.0]",0.0,0.0000,168,0.0,0
3,181.0,5470.json,true,Pasco County schools have graduation rates sub...,education,heather-fiorentino,superintendent of Pasco County's public schools,Florida,republican,0.0,...,0.0,1.0,a press release,pisco county school graduate rate substantia h...,"[0.0, 1.0, 0.0, 0.0]",0.0,0.0000,181,-0.3,-1
4,187.0,8320.json,mostly-true,Today many Florida teachers are at risk of hav...,education,charlie-crist,0,Florida,democrat,15.0,...,19.0,2.0,a Tampa Bay Times op-ed,today mani florida teacher risk pay impact per...,"[0.241, 0.759, 0.0, -0.3612]",0.0,-0.3612,187,-0.3,-1

In [29]:
my_train = pd.read_csv('input_data/sentiment/my_train_with_raw.csv')
df = pd.read_csv('input_data/sentiment/imdb_sentiment.csv')
#vader_train =  pd.read_csv('input_data/train_sentiment.csv')

my_train = my_train.loc[:,['healine_text', 'clean', 'polarity']]
my_train.columns =['raw_text', 'clean_text', 'sentiment']

imdb_data = df.loc[:,['raw_text', 'clean_text', 'sentiment']]

full_data = test_merge.merge(imdb_data, how = 'outer')
print(full_data.size)

full_data.dropna(inplace = True)
print(full_data.size)

full_data.to_csv('input_data/sentiment/imdb_and_liar.csv')

78867
75153

In [17]:
imdb_data = df.loc[:,['raw_text', 'clean_text', 'sentiment']]
imdb_data.head()

,raw_text,clean_text,sentiment
0,Working with one of the best Shakespeare sourc...,work one best shakespear sourc film manag cred...,-1
1,"Well...tremors I, the original started off in ...",well tremor origin start found movi quit enjoy...,-1
2,Ouch! This one was a bit painful to sit throug...,ouch one bit pain sit cute amus premis go hell...,-1
3,"I've seen some crappy movies in my life, but t...",seen crappi movi life one must among worst def...,-1
4,"""Carriers"" follows the exploits of two guys an...",carrier follow exploit two guy two gal stolen ...,-1

In [20]:
test_merge.columns =['raw_text', 'clean_text', 'sentiment']
test_merge.head()

,raw_text,clean_text,sentiment
0,Rebuilding three high schools will benefit 40 ...,rebuild three high school benefit percent port...,0
1,On an income cap for recipients of the popular...,incom cap recipe popular hope scholarship,0
2,Says states mandated tests come from an Englis...,say state mandat test come english company,0
3,Pasco County schools have graduation rates sub...,pisco county school graduate rate substantia h...,-1
4,Today many Florida teachers are at risk of hav...,today mani florida teacher risk pay impact per...,-1

In [22]:
full_data = test_merge.merge(imdb_data, how = 'outer')
print(full_data.size)
full_data.head()
full_data.to_csv('input_data/sentiment/imdb_and_liar.csv')

78867

In [26]:
full_data.dropna(inplace = True)
print(full_data.size)

75153

In [32]:
test = pd.read_csv('input_data/test_sentiment.csv')
test.head()

,Unnamed: 0,jsonid,label,headline_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,falsecounts,halftruecounts,mostlytrueocunts,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score
0,80,2854.json,pants-fire,Rebuilding three high schools will benefit 40 ...,education,carole-smith,Portland schools superintendent,Oregon,none,0.0,0.0,0.0,0.0,1.0,a press briefing,rebuild three high school benefit percent port...,"[0.0, 0.75, 0.25, 0.4588]",0,0.4588
1,124,10147.json,false,On an income cap for recipients of the popular...,education,jason-carter,State Senator,Georgia,democrat,1.0,0.0,2.0,1.0,0.0,forum,incom cap recipe popular hope scholarship,"[0.0, 0.412, 0.588, 0.6908]",1,0.6908
2,168,7744.json,mostly-true,Says states mandated tests come from an Englis...,education,george-lavender,State representative,Texas,republican,0.0,0.0,0.0,1.0,0.0,in Texas House of Representatives debate,say state mandat test come english company,"[0.0, 1.0, 0.0, 0.0]",0,0.0000
3,181,5470.json,true,Pasco County schools have graduation rates sub...,education,heather-fiorentino,superintendent of Pasco County's public schools,Florida,republican,0.0,0.0,1.0,0.0,1.0,a press release,pisco county school graduate rate substantia h...,"[0.0, 1.0, 0.0, 0.0]",0,0.0000
4,187,8320.json,mostly-true,Today many Florida teachers are at risk of hav...,education,charlie-crist,0,Florida,democrat,15.0,9.0,20.0,19.0,2.0,a Tampa Bay Times op-ed,today mani florida teacher risk pay impact per...,"[0.241, 0.759, 0.0, -0.3612]",0,-0.3612

In [34]:
data = pd.read_csv('input_data/sentiment/imdb_sentiment.csv')
data.head()

,Unnamed: 0,Unnamed: 0.1,raw_text,sentiment,clean_text
0,0,0,Working with one of the best Shakespeare sourc...,-1,work one best shakespear sourc film manag cred...
1,1,1,"Well...tremors I, the original started off in ...",-1,well tremor origin start found movi quit enjoy...
2,2,2,Ouch! This one was a bit painful to sit throug...,-1,ouch one bit pain sit cute amus premis go hell...
3,3,3,"I've seen some crappy movies in my life, but t...",-1,seen crappi movi life one must among worst def...
4,4,4,"""Carriers"" follows the exploits of two guys an...",-1,carrier follow exploit two guy two gal stolen ...

In [35]:
tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')

x = tfidfV.fit_transform(df['clean_text'])
print(x.shape)

(25000, 11246)

In [42]:
print(x[1,:])

  (0, 10150)	0.8592765763586055
  (0, 966)	0.3071349850466743
  (0, 2931)	0.2864255254528685
  (0, 7792)	0.2920141857014158

In [43]:
log_model = LogisticRegression(solver='liblinear', C=32/100)
log_model.fit(x, data['sentiment'])

LogisticRegression(C=0.32, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [44]:
log_model.predict(x[1,:])

array([-1])

In [49]:
test.loc[1,['clean']]

clean    incom cap recipe popular hope scholarship
Name: 1, dtype: object

In [50]:
tfidfV.transform(test.loc[1,['clean']])

<1x11246 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [59]:
#data source  = https://medium.com/@murphystude/can-computers-learn-to-be-funny-e184c340d772

onion_data = pd.read_csv('/Users/jonathan/Downloads/onion_headlines.txt', sep = '\n', header = None)
onion_data.columns = ['raw_text']
onion_data.dropna(inplace = True)
onion_data.head()

                                            raw_text
0  Weird Kid Opts To Sit Perfectly Still, Let Uni...
1   Kamala Harris Enters 2020 Race #WhatDoYouThink?
2  Viral Video Sparks National Debate Around Drum...
3  Kamala Harris Assembles Campaign Staff Of Unpa...
4  Study Finds Chimpanzees Only Other Animal Capa...

In [67]:
#cleaning(onion_data.loc[0,'raw_text'])

onion_data['clean'] = onion_data.applymap(cleaning)

In [68]:
onion_data.head()

,raw_text,clean
0,"Weird Kid Opts To Sit Perfectly Still, Let Uni...",weird kid opt sit perfect still let univers de...
1,Kamala Harris Enters 2020 Race #WhatDoYouThink?,kamala harri enter race whatdoyouthink
2,Viral Video Sparks National Debate Around Drum...,viral video spark nation debat around drum public
3,Kamala Harris Assembles Campaign Staff Of Unpa...,kamala harri assembl campaign staff unpaid cal...
4,Study Finds Chimpanzees Only Other Animal Capa...,studi find chimpanze anim capabl keep lid frie...

In [70]:
no_satire = pd.read_csv('/Users/jonathan/Downloads/notsatire.txt', sep = '\n', header = None, names = ['raw_text'])
print(no_satire.shape)
no_satire.head()

(8702, 1)

                                            raw_text
0  Even before a fireball in Tlahuelilpan killed ...
1  The convention defines who is a diplomat and t...
2  Unless a plan gets some senators to cross the ...
3  Brady Corbet uses a wide variety of gimmicks t...
4  Countries in west and central Africa have impo...

In [71]:
no_satire['clean'] = no_satire.applymap(cleaning)
no_satire.head()

,raw_text,clean
0,Even before a fireball in Tlahuelilpan killed ...,even firebal tlahuelilpan kill least peopl fue...
1,The convention defines who is a diplomat and t...,convent defin diplomat thus entitl special pri...
2,Unless a plan gets some senators to cross the ...,unless plan get senat cross aisl shutdown go
3,Brady Corbet uses a wide variety of gimmicks t...,bradi corbet us wide varieti gimmick mask hear...
4,Countries in west and central Africa have impo...,countri west central africa import central ban...

In [132]:
onion_data['label'] = -1
onion_data.drop_duplicates(inplace = True)

no_satire['label'] = 1
no_satire.drop_duplicates(inplace= True)


onion_set = onion_data.merge(no_satire.sample(len(onion_data)), how = 'outer')
onion_set.to_csv('input_data/sentiment/onion_set_balanced.csv')

onion_set = onion_data.merge(no_satire, how = 'outer')
onion_set.to_csv('input_data/sentiment/onion_set_full.csv')

In [162]:
onion_balanced = pd.read_csv('input_data/sentiment/onion_set_balanced.csv')

sentiment = []
vader_pol = []
cmp_score = []
for row in onion_balanced['clean']:
    get_pols = get_polarity_type(str(row))
    sentiment.append(get_pols[1:])
    vader_pol.append(get_pols[0])
    cmp_score.append(get_pols[1:][-1]) #last element 
    
onion_balanced['sentiment_vector'] = sentiment
onion_balanced['vader_polarity'] = vader_pol
onion_balanced['sentiment_score'] = cmp_score

onion_balanced.head()

,Unnamed: 0,raw_text,clean,label,sentiment_vector,vader_polarity,sentiment_score
0,0,"Weird Kid Opts To Sit Perfectly Still, Let Uni...",weird kid opt sit perfect still let univers de...,-1,"[0.098, 0.69, 0.213, 0.4588]",0,0.4588
1,1,Kamala Harris Enters 2020 Race #WhatDoYouThink?,kamala harri enter race whatdoyouthink,-1,"[0.0, 1.0, 0.0, 0.0]",0,0.0000
2,2,Viral Video Sparks National Debate Around Drum...,viral video spark nation debat around drum public,-1,"[0.0, 0.787, 0.213, 0.2263]",0,0.2263
3,3,Kamala Harris Assembles Campaign Staff Of Unpa...,kamala harri assembl campaign staff unpaid cal...,-1,"[0.292, 0.708, 0.0, -0.5106]",0,-0.5106
4,4,Study Finds Chimpanzees Only Other Animal Capa...,studi find chimpanze anim capabl keep lid frie...,-1,"[0.0, 0.714, 0.286, 0.4939]",0,0.4939

In [134]:
onion_balanced['vader_polarity'].describe()

count    3376.000000
mean       -0.009479
std         0.295996
min        -1.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: vader_polarity, dtype: float64

In [105]:
cdist([onion_balanced.loc[0,['sentiment_score','vader_polarity']]], onion_balanced.loc[2:,['sentiment_score','vader_polarity']], metric = 'cosine')

array([[ 0.,  2.,  0., ..., nan,  2.,  0.]])

In [107]:
onion_balanced.groupby('vader_polarity').count()

,Unnamed: 0,raw_text,clean,label,sentiment_vector,sentiment_score
vader_polarity,,,,,,
-1,167,167,167,167,167,167
0,3444,3444,3432,3444,3444,3444
1,185,185,185,185,185,185

In [163]:
for index, row in onion_balanced.iterrows():
    onion_balanced.loc[index,'sentiment_0'] = row['sentiment_vector'][0]
    onion_balanced.loc[index,'sentiment_1'] = row['sentiment_vector'][1]
    onion_balanced.loc[index,'sentiment_2'] = row['sentiment_vector'][2]

In [164]:
print(onion_balanced.shape)
onion_balanced.head()

(3376, 10)

,Unnamed: 0,raw_text,clean,label,sentiment_vector,vader_polarity,sentiment_score,sentiment_0,sentiment_1,sentiment_2
0,0,"Weird Kid Opts To Sit Perfectly Still, Let Uni...",weird kid opt sit perfect still let univers de...,-1,"[0.098, 0.69, 0.213, 0.4588]",0,0.4588,0.098,0.690,0.213
1,1,Kamala Harris Enters 2020 Race #WhatDoYouThink?,kamala harri enter race whatdoyouthink,-1,"[0.0, 1.0, 0.0, 0.0]",0,0.0000,0.000,1.000,0.000
2,2,Viral Video Sparks National Debate Around Drum...,viral video spark nation debat around drum public,-1,"[0.0, 0.787, 0.213, 0.2263]",0,0.2263,0.000,0.787,0.213
3,3,Kamala Harris Assembles Campaign Staff Of Unpa...,kamala harri assembl campaign staff unpaid cal...,-1,"[0.292, 0.708, 0.0, -0.5106]",0,-0.5106,0.292,0.708,0.000
4,4,Study Finds Chimpanzees Only Other Animal Capa...,studi find chimpanze anim capabl keep lid frie...,-1,"[0.0, 0.714, 0.286, 0.4939]",0,0.4939,0.000,0.714,0.286

In [165]:
onion_balanced['clean'] = onion_balanced['clean'].apply(str)

In [166]:
onion_balanced.to_csv('input_data/sentiment/onion_set_balanced.csv')

In [168]:
tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')


x = tfidfV.fit_transform(onion_balanced['clean'])
print(x.shape)

(3376, 1559)

In [142]:
liar_train = pd.read_csv('input_data/sentiment/liar_liar_train.csv')
print(liar_train.shape)
liar_train.head()

(260, 19)

,Unnamed: 0,jsonid,label,headline_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,falsecounts,halftruecounts,mostlytrueocunts,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score
0,5,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece,chicago bear start quarterback last year total...,"[0.335, 0.6, 0.065, -0.7506]",0,-0.7506
1,51,13210.json,barely-true,"Maggie Hassan raised tuition, making it the hi...",education,national-republican-senatorial-committee,0,0,republican,11.0,5.0,7.0,2.0,5.0,an ad,magi hassan rais tuition make highest america,"[0.0, 1.0, 0.0, 0.0]",0,0.0000
2,97,7599.json,mostly-true,"The average student in Florida, what they actu...",education,will-weatherford,State Representative,Florida,republican,2.0,3.0,4.0,3.0,0.0,a Board of Governors meeting,averag student florida actual pay pocket major...,"[0.104, 0.896, 0.0, -0.1027]",0,-0.1027
3,123,9500.json,mostly-true,Gov. Rick Scott cut the cost of prepaid colleg...,education,republican-party-florida,0,0,republican,10.0,6.0,6.0,6.0,4.0,a TV ad,gov rick scott cut cost prepaid college tuitio...,"[0.208, 0.792, 0.0, -0.2732]",0,-0.2732
4,280,12497.json,true,"Since 1978, college tuition nationwide has gon...",education,scott-walker,Milwaukee County Executive,Wisconsin,republican,26.0,41.0,32.0,40.0,11.0,a radio interview,sinc college tuition nationwide gone cometh li...,"[0.0, 0.8, 0.2, 0.3612]",0,0.3612

In [143]:
tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')


x = tfidfV.fit_transform(liar_train['clean'])
print(x.shape)

(260, 89)

In [145]:
liar_train.rename(columns = {'label':'liar_liar_label'}, inplace = True)

In [144]:
liar_train.groupby('label').count()

,Unnamed: 0,jsonid,headline_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,falsecounts,halftruecounts,mostlytrueocunts,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score
label,,,,,,,,,,,,,,,,,,
barely-true,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34
false,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48
half-true,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52
mostly-true,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63
pants-fire,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
true,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54

In [146]:
def convert_to_label(label):
    if(label == 'true'):
        return 1
    if(label == 'mostly-true'):
        return 1
    if(label == 'half-true'):
        return 0
    if(label == 'barely-true'):
        return -1
    if(label == 'false'):
        return -1
    if(label == 'pants-fire'):
        return -1

In [147]:
liar_train['label'] = liar_train['liar_liar_label'].apply(convert_to_label)

In [152]:
sentiment = []
vader_pol = []
cmp_score = []
for row in liar_train['clean']:
    get_pols = get_polarity_type(str(row))
    sentiment.append(get_pols[1:])
    vader_pol.append(get_pols[0])
    cmp_score.append(get_pols[1:][-1]) #last element 
    
liar_train['sentiment_vector'] = sentiment
liar_train['vader_polarity'] = vader_pol
liar_train['sentiment_score'] = cmp_score

liar_train.head()

[0, 0.335, 0.6, 0.065, -0.7506]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.104, 0.896, 0.0, -0.1027]
[0, 0.208, 0.792, 0.0, -0.2732]
[0, 0.0, 0.8, 0.2, 0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.412, 0.588, 0.0, -0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.887, 0.113, 0.5719]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.818, 0.182, 0.4404]
[0, 0.13, 0.87, 0.0, -0.2732]
[0, 0.19, 0.612, 0.197, 0.0516]
[0, 0.0, 0.815, 0.185, 0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.647, 0.353, 0.6124]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.111, 0.889, 0.0, -0.128]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.576, 0.424, 0.5994]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.264, 0.736, 0.0, -0.6486]
[0, 0.323, 0.677, 0.0, -0.6486]
[0, 0.097, 0.778, 0.125, 0.1779]
[0, 0.0, 0.805, 0.195, 0.4404]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.583, 0.417, 0.6124]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.244, 0.568, 0.188, -0.4588]
[0, 0.0, 0.755, 0.245, 0.6369]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.192, 0.615, 0.192, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.526, 0.474, 0.4019]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.853, 0.147, 0.2263]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.201, 0.714, 0.084, -0.4215]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.173, 0.827, 0.0, -0.3182]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.787, 0.213, 0.4019]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.149, 0.851, 0.0, -0.2732]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.463, 0.537, 0.0, -0.8591]
[0, 0.0, 0.864, 0.136, 0.296]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.68, 0.32, 0.5739]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.753, 0.247, 0.3818]
[0, 0.0, 0.885, 0.115, 0.0772]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.217, 0.783, 0.0, -0.3612]
[0, 0.468, 0.532, 0.0, -0.5267]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.792, 0.208, 0.2732]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.841, 0.159, 0.1779]
[0, 0.18, 0.82, 0.0, -0.296]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.899, 0.101, 0.2023]
[0, 0.0, 0.778, 0.222, 0.5719]
[0, 0.16, 0.84, 0.0, -0.2732]
[0, 0.206, 0.794, 0.0, -0.3818]
[0, 0.0, 0.795, 0.205, 0.2023]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.775, 0.225, 0.4404]
[0, 0.304, 0.696, 0.0, -0.5423]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.597, 0.403, 0.4019]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.144, 0.856, 0.0, -0.4019]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.891, 0.109, 0.0258]
[0, 0.185, 0.815, 0.0, -0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.667, 0.333, 0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.302, 0.698, 0.0, -0.6369]
[0, 0.375, 0.625, 0.0, -0.34]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.394, 0.606, 0.0, -0.3818]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.815, 0.185, 0.34]
[0, 0.191, 0.545, 0.264, 0.2023]
[1, 0.0, 0.417, 0.583, 0.6369]
[0, 0.0, 0.809, 0.191, 0.3818]
[0, 0.0, 0.762, 0.238, 0.3612]
[0, 0.0, 0.706, 0.294, 0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.206, 0.685, 0.109, -0.34]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.226, 0.522, 0.252, 0.0772]
[0, 0.424, 0.576, 0.0, -0.7096]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.769, 0.231, 0.5106]
[0, 0.0, 0.746, 0.254, 0.7579]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.294, 0.706, 0.0, -0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.704, 0.296, 0.6369]
[0, 0.0, 0.805, 0.195, 0.5267]
[0, 0.0, 0.734, 0.266, 0.4404]
[0, 0.104, 0.896, 0.0, -0.1027]
[0, 0.0, 0.597, 0.403, 0.4019]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.727, 0.273, 0.4588]
[0, 0.231, 0.769, 0.0, -0.2732]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.795, 0.205, 0.2023]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.183, 0.714, 0.103, -0.25]
[1, 0.0, 0.465, 0.535, 0.3182]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.29, 0.71, 0.0, -0.5423]
[0, 0.0, 0.647, 0.353, 0.4404]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.16, 0.84, 0.0, -0.2732]
[0, 0.0, 0.726, 0.274, 0.5267]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.833, 0.167, 0.4939]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.216, 0.784, 0.0, -0.296]
[0, 0.0, 0.633, 0.367, 0.4404]
[0, 0.0, 0.629, 0.371, 0.7096]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.271, 0.729, 0.0, -0.3818]
[0, 0.0, 0.82, 0.18, 0.296]
[0, 0.0, 0.915, 0.085, 0.0772]
[0, 0.0, 0.885, 0.115, 0.0772]
[0, 0.0, 0.874, 0.126, 0.0772]
[1, 0.0, 0.396, 0.604, 0.7269]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[1, 0.0, 0.465, 0.535, 0.8885]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.838, 0.162, 0.4404]
[0, 0.0, 0.829, 0.171, 0.7783]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[1, 0.0, 0.379, 0.621, 0.802]
[0, 0.2, 0.8, 0.0, -0.3612]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.828, 0.172, 0.4404]
[0, 0.0, 0.756, 0.244, 0.4404]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.915, 0.085, 0.0772]
[0, 0.161, 0.839, 0.0, -0.2755]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.686, 0.314, 0.4939]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.508, 0.492, 0.891]
[0, 0.113, 0.887, 0.0, -0.1027]
[0, 0.0, 0.647, 0.353, 0.5994]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.69, 0.31, 0.5423]
[0, 0.0, 0.742, 0.258, 0.1877]
[0, 0.0, 0.794, 0.206, 0.0772]
[0, 0.121, 0.603, 0.276, 0.4215]
[0, 0.162, 0.615, 0.223, 0.2023]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.565, 0.435, 0.6597]
[0, 0.0, 0.776, 0.224, 0.3818]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[-1, 0.438, 0.432, 0.13, -0.6124]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.678, 0.322, 0.5859]
[0, 0.222, 0.778, 0.0, -0.25]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.122, 0.612, 0.265, 0.4215]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.412, 0.588, 0.0, -0.5994]
[0, 0.0, 0.575, 0.425, 0.5719]
[0, 0.0, 0.69, 0.31, 0.4019]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.513, 0.487, 0.5859]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.755, 0.245, 0.3818]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.444, 0.556, 0.0, -0.6808]

,Unnamed: 0,jsonid,liar_liar_label,headline_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,...,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score,label,sentiment_0,sentiment_1,sentiment_2
0,5,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,...,1.0,a an online opinion-piece,chicago bear start quarterback last year total...,"[0.335, 0.6, 0.065, -0.7506]",0,-0.7506,1,[,0,.
1,51,13210.json,barely-true,"Maggie Hassan raised tuition, making it the hi...",education,national-republican-senatorial-committee,0,0,republican,11.0,...,5.0,an ad,magi hassan rais tuition make highest america,"[0.0, 1.0, 0.0, 0.0]",0,0.0000,-1,[,0,.
2,97,7599.json,mostly-true,"The average student in Florida, what they actu...",education,will-weatherford,State Representative,Florida,republican,2.0,...,0.0,a Board of Governors meeting,averag student florida actual pay pocket major...,"[0.104, 0.896, 0.0, -0.1027]",0,-0.1027,1,[,0,.
3,123,9500.json,mostly-true,Gov. Rick Scott cut the cost of prepaid colleg...,education,republican-party-florida,0,0,republican,10.0,...,4.0,a TV ad,gov rick scott cut cost prepaid college tuitio...,"[0.208, 0.792, 0.0, -0.2732]",0,-0.2732,1,[,0,.
4,280,12497.json,true,"Since 1978, college tuition nationwide has gon...",education,scott-walker,Milwaukee County Executive,Wisconsin,republican,26.0,...,11.0,a radio interview,sinc college tuition nationwide gone cometh li...,"[0.0, 0.8, 0.2, 0.3612]",0,0.3612,1,[,0,.

In [153]:
for index, row in liar_train.iterrows():
    liar_train.loc[index,'sentiment_0'] = row['sentiment_vector'][0]
    liar_train.loc[index,'sentiment_1'] = row['sentiment_vector'][1]
    liar_train.loc[index,'sentiment_2'] = row['sentiment_vector'][2]

In [154]:
liar_train.head()

,Unnamed: 0,jsonid,liar_liar_label,headline_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,...,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score,label,sentiment_0,sentiment_1,sentiment_2
0,5,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,...,1.0,a an online opinion-piece,chicago bear start quarterback last year total...,"[0.335, 0.6, 0.065, -0.7506]",0,-0.7506,1,0.335,0.6,0.065
1,51,13210.json,barely-true,"Maggie Hassan raised tuition, making it the hi...",education,national-republican-senatorial-committee,0,0,republican,11.0,...,5.0,an ad,magi hassan rais tuition make highest america,"[0.0, 1.0, 0.0, 0.0]",0,0.0000,-1,0,1,0
2,97,7599.json,mostly-true,"The average student in Florida, what they actu...",education,will-weatherford,State Representative,Florida,republican,2.0,...,0.0,a Board of Governors meeting,averag student florida actual pay pocket major...,"[0.104, 0.896, 0.0, -0.1027]",0,-0.1027,1,0.104,0.896,0
3,123,9500.json,mostly-true,Gov. Rick Scott cut the cost of prepaid colleg...,education,republican-party-florida,0,0,republican,10.0,...,4.0,a TV ad,gov rick scott cut cost prepaid college tuitio...,"[0.208, 0.792, 0.0, -0.2732]",0,-0.2732,1,0.208,0.792,0
4,280,12497.json,true,"Since 1978, college tuition nationwide has gon...",education,scott-walker,Milwaukee County Executive,Wisconsin,republican,26.0,...,11.0,a radio interview,sinc college tuition nationwide gone cometh li...,"[0.0, 0.8, 0.2, 0.3612]",0,0.3612,1,0,0.8,0.2

In [170]:
liar_train.rename(columns = {'headline_text': 'raw_text'}, inplace = True)
liar_train.head()

,Unnamed: 0,jsonid,liar_liar_label,raw_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,...,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score,label,sentiment_0,sentiment_1,sentiment_2
0,5,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,...,1.0,a an online opinion-piece,chicago bear start quarterback last year total...,"[0.335, 0.6, 0.065, -0.7506]",0,-0.7506,1,0.335,0.6,0.065
1,51,13210.json,barely-true,"Maggie Hassan raised tuition, making it the hi...",education,national-republican-senatorial-committee,0,0,republican,11.0,...,5.0,an ad,magi hassan rais tuition make highest america,"[0.0, 1.0, 0.0, 0.0]",0,0.0000,-1,0,1,0
2,97,7599.json,mostly-true,"The average student in Florida, what they actu...",education,will-weatherford,State Representative,Florida,republican,2.0,...,0.0,a Board of Governors meeting,averag student florida actual pay pocket major...,"[0.104, 0.896, 0.0, -0.1027]",0,-0.1027,1,0.104,0.896,0
3,123,9500.json,mostly-true,Gov. Rick Scott cut the cost of prepaid colleg...,education,republican-party-florida,0,0,republican,10.0,...,4.0,a TV ad,gov rick scott cut cost prepaid college tuitio...,"[0.208, 0.792, 0.0, -0.2732]",0,-0.2732,1,0.208,0.792,0
4,280,12497.json,true,"Since 1978, college tuition nationwide has gon...",education,scott-walker,Milwaukee County Executive,Wisconsin,republican,26.0,...,11.0,a radio interview,sinc college tuition nationwide gone cometh li...,"[0.0, 0.8, 0.2, 0.3612]",0,0.3612,1,0,0.8,0.2

In [171]:
liar_train.to_csv('input_data/sentiment/liar_liar_train.csv')

In [158]:
liar_test = pd.read_csv('input_data/sentiment/liar_liar_test.csv')
#liar_test.rename(columns = {'label':'liar_liar_label'}, inplace = True)
#liar_test['label'] = liar_test['liar_liar_label'].apply(convert_to_label)

sentiment = []
vader_pol = []
cmp_score = []
for row in liar_test['clean']:
    get_pols = get_polarity_type(str(row))
    sentiment.append(get_pols[1:])
    vader_pol.append(get_pols[0])
    cmp_score.append(get_pols[1:][-1]) #last element 
    
liar_test['sentiment_vector'] = sentiment
liar_test['vader_polarity'] = vader_pol
liar_test['sentiment_score'] = cmp_score

for index, row in liar_test.iterrows():
    liar_test.loc[index,'sentiment_0'] = row['sentiment_vector'][0]
    liar_test.loc[index,'sentiment_1'] = row['sentiment_vector'][1]
    liar_test.loc[index,'sentiment_2'] = row['sentiment_vector'][2]
    
    
liar_test.to_csv('input_data/sentiment/liar_liar_test.csv')

[0, 0.0, 0.75, 0.25, 0.4588]
[1, 0.0, 0.412, 0.588, 0.6908]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.241, 0.759, 0.0, -0.3612]
[0, 0.333, 0.667, 0.0, -0.5423]
[0, 0.0, 0.752, 0.248, 0.5106]
[0, 0.174, 0.826, 0.0, -0.2732]
[0, 0.0, 0.948, 0.052, 0.0258]
[0, 0.0, 0.845, 0.155, 0.296]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.212, 0.788, 0.0, -0.5423]
[0, 0.189, 0.811, 0.0, -0.1027]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.252, 0.748, 0.0, -0.4019]
[0, 0.1, 0.813, 0.086, -0.0772]
[1, 0.0, 0.488, 0.512, 0.743]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.755, 0.245, 0.3818]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.189, 0.811, 0.0, -0.2732]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.42, 0.58, 0.0, -0.4404]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.221, 0.779, 0.0, -0.1779]
[0, 0.0, 0.526, 0.474, 0.5574]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 0.84, 0.16, 0.2732]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.467, 0.533, 0.0, -0.5423]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.211, 0.789, 0.0, -0.34]
[0, 0.296, 0.704, 0.0, -0.2732]
[0, 0.0, 0.648, 0.352, 0.5859]
[0, 0.0, 1.0, 0.0, 0.0]
[0, 0.0, 1.0, 0.0, 0.0]

In [172]:
liar_test.rename(columns = {'headline_text': 'raw_text'}, inplace = True)
liar_test.head()

,Unnamed: 0,jsonid,liar_liar_label,raw_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,barelytruecounts,...,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score,label,sentiment_0,sentiment_1,sentiment_2
0,80,2854.json,pants-fire,Rebuilding three high schools will benefit 40 ...,education,carole-smith,Portland schools superintendent,Oregon,none,0.0,...,1.0,a press briefing,rebuild three high school benefit percent port...,"[0.0, 0.75, 0.25, 0.4588]",0,0.4588,-1,0.000,0.750,0.250
1,124,10147.json,false,On an income cap for recipients of the popular...,education,jason-carter,State Senator,Georgia,democrat,1.0,...,0.0,forum,incom cap recipe popular hope scholarship,"[0.0, 0.412, 0.588, 0.6908]",1,0.6908,-1,0.000,0.412,0.588
2,168,7744.json,mostly-true,Says states mandated tests come from an Englis...,education,george-lavender,State representative,Texas,republican,0.0,...,0.0,in Texas House of Representatives debate,say state mandat test come english company,"[0.0, 1.0, 0.0, 0.0]",0,0.0000,1,0.000,1.000,0.000
3,181,5470.json,true,Pasco County schools have graduation rates sub...,education,heather-fiorentino,superintendent of Pasco County's public schools,Florida,republican,0.0,...,1.0,a press release,pisco county school graduate rate substantia h...,"[0.0, 1.0, 0.0, 0.0]",0,0.0000,1,0.000,1.000,0.000
4,187,8320.json,mostly-true,Today many Florida teachers are at risk of hav...,education,charlie-crist,0,Florida,democrat,15.0,...,2.0,a Tampa Bay Times op-ed,today mani florida teacher risk pay impact per...,"[0.241, 0.759, 0.0, -0.3612]",0,-0.3612,1,0.241,0.759,0.000

In [173]:
liar_test.to_csv('input_data/sentiment/liar_liar_test.csv')

In [169]:
onion_balanced = pd.read_csv('input_data/sentiment/onion_set_balanced.csv')
onion_balanced.head()

,Unnamed: 0,Unnamed: 0.1,raw_text,clean,label,sentiment_vector,vader_polarity,sentiment_score,sentiment_0,sentiment_1,sentiment_2
0,0,0,"Weird Kid Opts To Sit Perfectly Still, Let Uni...",weird kid opt sit perfect still let univers de...,-1,"[0.098, 0.69, 0.213, 0.4588]",0,0.4588,0.098,0.690,0.213
1,1,1,Kamala Harris Enters 2020 Race #WhatDoYouThink?,kamala harri enter race whatdoyouthink,-1,"[0.0, 1.0, 0.0, 0.0]",0,0.0000,0.000,1.000,0.000
2,2,2,Viral Video Sparks National Debate Around Drum...,viral video spark nation debat around drum public,-1,"[0.0, 0.787, 0.213, 0.2263]",0,0.2263,0.000,0.787,0.213
3,3,3,Kamala Harris Assembles Campaign Staff Of Unpa...,kamala harri assembl campaign staff unpaid cal...,-1,"[0.292, 0.708, 0.0, -0.5106]",0,-0.5106,0.292,0.708,0.000
4,4,4,Study Finds Chimpanzees Only Other Animal Capa...,studi find chimpanze anim capabl keep lid frie...,-1,"[0.0, 0.714, 0.286, 0.4939]",0,0.4939,0.000,0.714,0.286

In [280]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import  LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem.porter import *
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

class SentimentAnalysis():

    def __init__(self):        
        
        liar_liar_train = pd.read_csv('input_data/sentiment/liar_liar_train.csv')
        liar_liar_test = pd.read_csv('input_data/sentiment/liar_liar_test.csv')
        onion_balanced = pd.read_csv('input_data/sentiment/onion_set_balanced.csv')
        
        col = ['raw_text', 'clean', 'label', 'vader_polarity', 'sentiment_score', 'sentiment_0', 'sentiment_1', 'sentiment_2']
        
        liar_liar_train = liar_liar_train.loc[:,col]
        onion_balanced = onion_balanced.loc[:,col]
        
        full_train = liar_liar_train.merge(onion_balanced, how = 'outer')
        full_train.dropna(inplace = True)
        
        compare_col = ['vader_polarity', 'sentiment_score', 'sentiment_0', 'sentiment_1', 'sentiment_2']

        tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')
#         tfidf_matrix = tfidfV.fit(full_train['clean'])
        
#         tfidf_matrix = pd.DataFrame(tfidf_matrix.toarray())
#         compare_set = full_train.loc[:,compare_col]
        
#         compare_set = pd.concat([compare_set, tfidf_matrix])
        
        
        
        
        self.logR_pipeline = Pipeline([
                ('LogRCV', tfidfV),
                ('LogR_clf',LogisticRegression(solver='liblinear', C=32/100))
                ])
        
        
#         self.logR_pipeline = Pipeline([
#                 ('LogRCV', tfidfV),
#                 ('LogR_clf',RandomForestClassifier(n_estimators=100, max_depth=8, random_state=0))
#                 ])
        

        self.logR_pipeline.fit(full_train['clean'],full_train['vader_polarity'])
        predicted_LogR = self.logR_pipeline.predict(liar_liar_train['clean'])
        score = metrics.accuracy_score(liar_liar_train['vader_polarity'], predicted_LogR)
        print("Sentiment Analysis Model Trained - accuracy:   %0.6f" % score)
        

    def predict(self, text):
        predicted = self.logR_pipeline.predict([text])
        predicedProb = self.logR_pipeline.predict_proba([text])[:,1]
        return bool(predicted), float(predicedProb)
    
    
sa = SentimentAnalysis()
sa.predict("Says the Annies List political group supports third-trimester abortions on demand.")

Sentiment Analysis Model Trained - accuracy:   0.976923

(False, 0.903965019080783)

In [312]:
liar_liar_train = pd.read_csv('input_data/sentiment/liar_liar_train.csv')
liar_liar_test = pd.read_csv('input_data/sentiment/liar_liar_test.csv')
onion_balanced = pd.read_csv('input_data/sentiment/onion_set_balanced.csv')

col = ['raw_text', 'clean', 'label', 'vader_polarity', 'sentiment_score', 'sentiment_0', 'sentiment_1', 'sentiment_2']

liar_liar_train = liar_liar_train.loc[:,col]
onion_balanced = onion_balanced.loc[:,col]

full_train = liar_liar_train.merge(onion_balanced, how = 'outer')
full_train.dropna(inplace=True)
full_train.reset_index(drop=True, inplace=True)



print('full train dim' + str(full_train.shape))
print('liar test dim' + str(liar_liar_test.shape))

compare_col = ['vader_polarity', 'sentiment_score', 'sentiment_0', 'sentiment_1', 'sentiment_2']

tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')
train_tfidf = tfidfV.fit_transform(full_train['clean'])
train_tfidf = pd.DataFrame(train_tfidf.toarray()).transpose()

pca_components = 4

print('train tfidf dim' + str(train_tfidf.shape))

pca = PCA(n_components=pca_components)
pca.fit(train_tfidf)

train_components =  pd.DataFrame(pca.components_).transpose()


print('train components dim' + str(train_components.shape))
print('full components dim' + str(full_train.loc[:,compare_col].shape))


compare_set = pd.concat([full_train.loc[:,compare_col], train_components],axis=1)

print('compare set dim' + str(compare_set.shape))

test_tfidf = tfidfV.transform(liar_liar_test['clean'])
test_tfidf = pd.DataFrame(test_tfidf.toarray()).transpose()

print('test tfidf dim' + str(test_tfidf.shape))

pca = PCA(n_components=pca_components)
pca.fit(test_tfidf)

test_components =  pd.DataFrame(pca.components_).transpose()

print('test components dim' + str(test_components.shape))

test_set = pd.concat([liar_liar_test.loc[:,compare_col], test_components] ,axis=1)

print('test set dim' + str(test_set.shape))

test_set.fillna(0, inplace = True)
compare_set.fillna(0, inplace = True)


#dist = cdist(liar_liar_test.loc[:,compare_col], full_train.loc[:,compare_col], metric = 'cosine')
dist = cdist(test_set, compare_set, metric = 'cosine')



predict = pd.DataFrame()
c = 0

for row in dist:
    predict.loc[c,'index'] = row.argmin()
    predict.loc[c,'dist'] = row[row.argmin()]
    c = c+1

for index, row in predict.iterrows():
    predict.loc[index, 'prediction'] = full_train.loc[row['index'], 'label']

predict.head()

score = metrics.accuracy_score(liar_liar_test['label'], predict['prediction'])

print("Sentiment Analysis Model Trained - accuracy:   %0.6f" % score)

#liar_liar_train.head()

full train dim(3630, 8)
liar test dim(51, 24)
train tfidf dim(1612, 3630)
train components dim(3630, 4)
full components dim(3630, 5)
compare set dim(3630, 9)
test tfidf dim(1612, 51)
test components dim(51, 4)
test set dim(51, 9)
Sentiment Analysis Model Trained - accuracy:   0.490196

In [358]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import  LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem.porter import *
from sklearn import metrics
import warnings
from IPython.display import display
warnings.filterwarnings('ignore')

class SentimentAnalysis():

    def __init__(self):        
        #load all datasets used, liar liar and onion headlines
        liar_liar_train = pd.read_csv('input_data/sentiment/liar_liar_train.csv')
        liar_liar_test = pd.read_csv('input_data/sentiment/liar_liar_test.csv')
        onion_balanced = pd.read_csv('input_data/sentiment/onion_set_balanced.csv')

        col = ['raw_text', 'clean', 'label', 'vader_polarity', 'sentiment_score', 'sentiment_0', 'sentiment_1', 'sentiment_2']

        liar_liar_train = liar_liar_train.loc[:,col]
        onion_balanced = onion_balanced.loc[:,col]
        
        #join the liar train and onion set
        self.full_train = liar_liar_train.merge(onion_balanced, how = 'outer')
        self.full_train.dropna(inplace=True)
        self.full_train.reset_index(drop=True, inplace=True)


        self.compare_col = ['vader_polarity', 'sentiment_score', 'sentiment_0', 'sentiment_1', 'sentiment_2']
        
        #create TF IDF 
        self.tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')
        train_tfidf = self.tfidfV.fit_transform(full_train['clean'])
        train_tfidf = pd.DataFrame(train_tfidf.toarray()).transpose()
    
        #reduce TF IDF matrix with PCA
        self.pca_components = 4

        pca = PCA(n_components=self.pca_components ,random_state = 0)
        pca.fit(train_tfidf)
        
        #components from the reduced TF IDF
        train_components =  pd.DataFrame(pca.components_).transpose()
        
        #for converting the input from predict
        pca.fit(train_tfidf.transpose())
        self.comp = pca.components_
        
        #full set of values that is used in cosine similarity
        self.compare_set = pd.concat([full_train.loc[:,self.compare_col], train_components],axis=1)
        
        #set up testing data
        test_tfidf = self.tfidfV.transform(liar_liar_test['clean'])
        test_tfidf = pd.DataFrame(test_tfidf.toarray()).transpose()

        pca.fit(test_tfidf)
        test_components =  pd.DataFrame(pca.components_).transpose()
        
        test_set = pd.concat([liar_liar_test.loc[:,self.compare_col], test_components] ,axis=1)
        
        #fill in NA from sparse matrices so cosine doesnt return NA
        test_set.fillna(0, inplace = True)
        self.compare_set.fillna(0, inplace = True)

        #build distances between the test set and train set
        #dist = cdist(liar_liar_test.loc[:,compare_col], full_train.loc[:,compare_col], metric = 'cosine')
        dist = cdist(test_set, compare_set, metric = 'cosine')

        #build prediction matrix
        predict = pd.DataFrame()
        c = 0

        #for each distance, get the min index, and the distance associated with it
        for row in dist:
            predict.loc[c,'index'] = row.argmin()
            predict.loc[c,'dist'] = row[row.argmin()]
            c = c+1

        #get the truth value from the closest document to the test
        for index, row in predict.iterrows():
            predict.loc[index, 'prediction'] = full_train.loc[row['index'], 'label']

        #score it
        score = metrics.accuracy_score(liar_liar_test['label'], predict['prediction'])

        print("Sentiment Analysis Model Trained - accuracy:   %0.6f" % score)

        #liar_liar_train.head()

    def predict(self, text):
        
        #convert the input text to dataframe to compare
        input_df = pd.DataFrame()
        #get the vader sentiment from input
        input_sentiment = get_polarity_type(text)
        input_df.loc[0,'raw_text'] = text
        input_df.loc[0,'clean'] = cleaning(text)
        input_df.loc[0,'vader_polarity'] = input_sentiment[0]
        input_df.loc[0,'sentiment_0'] = input_sentiment[1]
        input_df.loc[0,'sentiment_1'] = input_sentiment[2]
        input_df.loc[0,'sentiment_2'] = input_sentiment[3]
        input_df.loc[0,'sentiment_score'] = input_sentiment[4]
        
        #display(input_df)
        
        #get the TF IDF mapping from input with the TF IDF from the training set
        input_tfidf = self.tfidfV.transform(input_df['clean'])
        input_tfidf = pd.DataFrame(input_tfidf.toarray())
        
        #convert the input TF IDF to correct size since the training compare set has 4 PCA values, need to reduce the 
            #input TF IDF to 4 values
        #pca = PCA(n_components=self.pca_components)
        #input_components = pd.DataFrame(self.pca.transform(input_tfidf)).transpose()
        input_components = pd.DataFrame(np.matmul(input_tfidf.values, self.comp.transpose()))
        
        #build the input set to compare to the training set
        input_set = pd.concat([input_df.loc[:,self.compare_col], input_components] ,axis=1)
        
        #find the closest document in the training set
        dist = cdist(input_set, self.compare_set, metric = 'cosine')
        sim_index = dist.argmin()
        sim_dist = dist[0,dist.argmin()]
        
        #get the truth label from the closest in training set - that's the prediction
        predicted = self.full_train.loc[sim_index, 'label']
        #the probability is the 1-dist away from closest in training set.
        predicted_prob = 1-sim_dist;
        
        return bool(predicted), float(predicted_prob)
    
    
sa = SentimentAnalysis()
sa.predict("Says the Annies List political group supports third-trimester abortions on demand.")

Sentiment Analysis Model Trained - accuracy:   0.470588

,raw_text,clean,vader_polarity,sentiment_0,sentiment_1,sentiment_2,sentiment_score
0,Says the Annies List political group supports ...,say anni list polit group support third trimes...,0.0,0.115,0.692,0.192,0.25

input set shape(1, 9)
compare set shape(3630, 9)
dist shape(1, 3630)

(True, 0.999377333255142)

In [340]:
liar_liar_test.groupby('label').count()

,Unnamed: 0,Unnamed: 0.1,jsonid,liar_liar_label,raw_text,subject,speaker,speakerjobtitle,stateinfo,partyaffiliation,...,mostlytrueocunts,pantsonfirecounts,context,clean,sentiment_vector,vader_polarity,sentiment_score,sentiment_0,sentiment_1,sentiment_2
label,,,,,,,,,,,,,,,,,,,,,
-1,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
0,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
1,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19

In [252]:
for col in predict:
    print(predict[col].unique())

[3645    0]

In [292]:
print(full_train.shape)
tfidfV = TfidfVectorizer(stop_words='english', min_df=5, max_df=30, use_idf=True, smooth_idf=True, token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b')
tf_matrix = tfidfV.fit_transform(full_train['clean'])

out = pd.DataFrame(tf_matrix.toarray()).transpose()
pca = PCA(n_components=10)
pca.fit(out)
print(pca.explained_variance_ratio_)
components =  pd.DataFrame(pca.components_).transpose()
print(components.shape)
components.head()

(3630, 8)
[0.00325539 0.00240044 0.00232316 0.00228496 0.00227021 0.00218152
 0.00216733 0.00215717 0.00213121 0.00210548]
(3630, 10)

,0,1,2,3,4,5,6,7,8,9
0,0.003106,0.011659,0.005238,0.009125,0.000068,-0.013274,-0.019270,-0.013716,0.007864,-0.009934
1,0.051250,0.001543,-0.017752,0.000756,-0.025661,0.011686,0.012842,-0.005663,0.030247,0.002883
2,0.046155,-0.005000,-0.031754,-0.009487,0.030349,0.034870,0.045962,-0.022784,0.019751,-0.071802
3,0.022150,-0.002290,-0.025651,-0.010467,0.009168,0.029213,0.045808,-0.005329,0.042902,-0.044626
4,0.030615,-0.000563,-0.011087,-0.020334,0.001782,0.040125,0.031756,-0.018687,-0.005103,-0.027593

In [190]:
cat = pd.concat([out, full_train])
cat.shape

(7260, 1620)

In [202]:
cdist([out.loc[0,:]], out.loc[1:,:], metric = 'cosine').argmin()

14

In [204]:
out.loc[14,:].describe()

count    1612.000000
mean        0.000620
std         0.024907
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: 14, dtype: float64

In [205]:
out.loc[0,:].describe()

count    1612.000000
mean        0.001515
std         0.024868
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         0.441024
Name: 0, dtype: float64

In [240]:
a = np.array([[0, 0, 0],
               [0, 0, 1],
               [0, 1, 0],
               [0, 1, 1],
               [1, 0, 0],
               [1, 0, 1],
               [1, 1, 0],
               [1, 1, 1]])
b = np.array([[ 0.1,  0.2,  0.4], [ 0.9,  0.9,  0.7]])
dist = distance.cdist(b, a, 'cityblock')

for row in dist:
    print(row.argmin())

0
7